# These are supported funding model platforms

github: HackUnderway
patreon: HackUnderway
ko_fi: hackunderway
buy_me_a_coffee: hackunderway
custom: ["https://www.paypal.com/paypalme/HackUnderway", "https://hackunderway.io"]
